config/routes.rb
Rails.application.routes.draw do

  resources :fav_episodes
  resources :notices
  get 'searcher/search'
  resources :fav_shows
  resources :episode_ratins
  resources :mailingl_forms
  devise_for :users,
    controllers: {:registrations => "registrations", omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :episode_comments
  resources :tv_show_comments
  resources :news
  resources :directors
  resources :actors
  resources :tv_shows do
    resources :episodes
  end
  resources :users
  get '/admin', to: 'users#admin'

  get '/fav', to: 'fav_shows#create'

  get '/fev', to: 'fav_episodes#create'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get '/user/favorite', to: 'users#favorite'

  root 'tv_shows#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
  belongs_to :tv_show
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new(:user_id => params[:user_id])
    @tv_shows = TvShow.all
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to root_path, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:user_id, :tv_show_id, :content)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(notice) do |f| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <br>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :tv_show %>
    <br>
    <%= f.collection_select(:tv_show_id, @tv_shows, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <br>
    <%= f.text_field :content %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :Save, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notices</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Tv show</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.user %></td>
        <td><%= notice.tv_show %></td>
        <td><%= notice.content %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @notice.user %>
</p>

<p>
  <strong>Tv show:</strong>
  <%= @notice.tv_show %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>