config/routes.rb
Rails.application.routes.draw do

  resources :fav_episodes
  resources :notices
  get 'searcher/search'
  resources :fav_shows
  resources :episode_ratins
  resources :mailingl_forms
  devise_for :users,
    controllers: {:registrations => "registrations", omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :episode_comments
  resources :tv_show_comments
  resources :news
  resources :directors
  resources :actors
  resources :tv_shows do
    resources :episodes
  end
  resources :users
  get '/admin', to: 'users#admin'

  get '/fav', to: 'fav_shows#create'

  get '/fev', to: 'fav_episodes#create'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get '/user/favorite', to: 'users#favorite'

  root 'tv_shows#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  enum role: [:child, :common, :admin]
  before_save :set_default_role, :if => :new_record?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, :default_url => ":style/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :tv_show_comments
  has_many :episode_comments
  has_many :news
  has_many :tv_show_ratings
  has_many :episode_ratings
  has_many :tv_shows, through: :tv_show_ratings
  has_many :episodes, through: :episode_ratings
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "father_id",
                                  dependent:   :destroy
  has_many :children, through: :active_relationships, source: :child
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "child_id",
                                   dependent:   :destroy
  has_many :fathers, through: :passive_relationships, source: :father

  def set_default_role
    puts "----------------------------"
    puts self.role
    if self.role == :child
      self.role ||= :child
    else
      self.role ||= :common
    end
    puts "+++++++++++++++++++++++++++++"
    puts self.role
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)
    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email = auth.info.email
      user = User.find_by(email: email) if email

      # Create the user if it's a new registration
      if user.nil?
        password = "123456"
        if auth.provider == 'facebook'
          user = User.new(
            email: email ? email : "#{auth.uid}@facebook.com",
            first_name: auth.info.first_name,
            last_name: auth.info.last_name,
            password: password,
            password_confirmation: password
          )
        end
      end
      user.save!
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end

    user
  end

  def email_verified?
    return true
    if self.email
      if self.email.split('@')[1] == 'facebook.com'
        return false
      else
        return true
      end
    else
      return false
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index, :admin]
  before_action :set_tv_shows, only: [:admin]

  # GET /users
  # GET /users.json
  def index
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @tv_shows = TvShow.where(user_id: params[:id]).order(created_at: :desc)
    @tv_shows = @tv_shows[0,4]

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }

      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin
    @tv_shows = TvShow.all
    @users = User.all
    @episodes = Episode.all
  end

  def finish_signup
    if request.patch? && params[:user] # Revisa si el request es de tipo patch, es decir, llenaron el formulario y lo ingresaron
      @user = User.find(params[:id])

      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to root_path, notice: 'Hemos guardado tu email correctamente.'
      else
        @show_errors = true
      end
    end
  end

  def favorite
    @series = FavShow.all
    @series_fav = []
    @tv_shows = TvShow.all
    @genders = Gender.all
    @directors = Director.all
    if user_signed_in?
      for i in @series
        if i.user_id == current_user.id and i.favorite
          @series_fav << @tv_shows.find(i.tv_show_id.to_i)
        end
      end
    end

    @episodes = FavEpisode.all
    @episodes_fav = []
    @tv_episodes = Episode.all
    if user_signed_in?
      for i in @episodes
        if i.user_id == current_user.id and i.favorite
          @episodes_fav << @tv_episodes.find(i.episode_id.to_i)
        end
      end
    end
  end

  private
    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(:first_name, :last_name, :role, :avatar, :email, accessible)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_users
      @users = User.all.sort_by{|e| [e.role, e.last_name, e.first_name]}
    end

    def set_tv_shows
      @tv_shows = TvShow.all.sort_by{|e| [e.name, e.country]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :role, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <% if current_user.role == "admin" %>
    <div class="field">
      <%= f.label :role %>
      <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admin.html.erb
<%= stylesheet_link_tag    'application' %>
<%= javascript_include_tag 'defaults' %>
<%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
<%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
<div class="col-sm-9 col-md-10" style="background-color:rgb(38, 38, 38)">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
                <li><a href="#users" data-toggle="tab"><span class="glyphicon glyphicon-user"></span>
                    User</a></li>
                <li><a href="#tvshows" data-toggle="tab"><span class="glyphicon glyphicon-film"></span>
                    TV Shows</a></li>
                <li><a href="#graphs" data-toggle="tab"><span class="glyphicon glyphicon-tags"></span>
                    Graphs</a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content" style="background-color:rgb(38, 38, 38)">
                <div class="tab-pane fade in active" style="background-color:rgb(38, 38, 38)" id="users">
                    <div class="list-group" style="background-color:rgb(38, 38, 38)">
                        <% @users.each do |user| %>
                          <li class="list-group-item" style="background-color:rgb(38, 38, 38)"><%= link_to user.last_name+', '+user.first_name, user_path(user), style: "color:white"%><div class="divider"/>
                            <span><%= user.role %></span>
                            <span class="pull-right" style="color:white"><%= button_to "edit", edit_user_path(user), class: "btn btn-info btn-xs", style: 'color:white', method: :get %> </span>
                            <span class="pull-right" style="color:rgb(38,38,38)"> - </span>
                            <span class="pull-right"> <%= button_to "delete", user_path(user), class: "btn btn-danger btn-xs", style: 'color:white', method: :delete %> </span></li>
                        <% end %>
                    </div>
                </div>
                <div class="tab-pane fade in" id="tvshows" style="background-color:rgb(38, 38, 38)">
                    <div class="list-group" style="background-color:rgb(38, 38, 38)">
                      <% @tv_shows.each do |tv_show| %>
                        <% owner = User.find(tv_show.user_id) %>
                        <li class="list-group-item" style="background-color:rgb(38, 38, 38)"><%= link_to tv_show.name, tv_show_path(tv_show), style: "color:white"%><div class="divider"/>
                          <span>Owner: <%= link_to owner.last_name+", "+owner.first_name, user_path(owner)  %></span>

                          <span class="pull-right"><%= button_to "edit", edit_tv_show_path(tv_show), class: "btn btn-info btn-xs", style: 'color:white', method: :get %> </span>
                          <span class="pull-right" style="color:rgb(38,38,38)"> - </span>
                          <span class="pull-right"> <%= button_to "delete", tv_show_path(tv_show), class: "btn btn-danger btn-xs", style: 'color:white', method: :delete %> </span>
                          </li>
                      <% end %>
                    </div>
                </div>

                <div class="tab-pane fade in" id="graphs">

                    <div class="col-xs-6">
                        <h> Series by country </h>
                        <%= pie_chart @tv_shows.group(:country).count %>

                        <h> Series by gender </h>
                        <%= pie_chart @tv_shows.group(:gender_id).count %>

                        <h> Series by directors </h>
                        <%= pie_chart @tv_shows.group(:director_id).count %>

                        <h> Series uploaded by week </h>
                        <%= line_chart @tv_shows.group_by_week(:created_at).count %>

                        <h> Episodes uploaded by week </h>
                        <%= line_chart @episodes.group_by_week(:created_at).count, discrete: true %>

                        <h> Episodes seen against unseen </h>
                        <%= pie_chart @episodes.group(:seen).count %>

                        <h> Episodes by rating </h>
                        <%= column_chart @episodes.group(:rating).count %>

                        <h> New users by month </h>
                        <%= line_chart @users.group_by_month(:created_at).count, discrete: true %>


                    </div>
                </div>
              </div>
        </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/favorite.html.erb
<p id="notice"><%= notice %></p>
<h2>Favoritos</h2>
<br>
<h3>Series</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Country</th>
      <th>Language</th>
      <th>Gender</th>
      <th>Director</th>
    </tr>
  </thead>
  <tbody>
    <% @series_fav.each do |serie| %>
      <tr>
      <td><%=link_to serie.name, serie %></td>
      <td><%= serie.description%></td>
      <td><%= serie.country%></td>
      <td><%= serie.language%></td>
      <%if serie.gender_id != nil%>
        <td><%= @genders.find(serie.gender_id).gender%></td>
      <%end%>
      <%if serie.director_id != nil%>
        <td><%= @directors.find(serie.director_id).first_name%></td>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
<h3>Episodes</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Season</th>
      <th>Duration</th>
      <th>Serie</th>
    </tr>
  </thead>
  <tbody>
    <% @episodes_fav.each do |serie| %>
      <tr>
      <td><%= serie.name %></td>
      <td><%= serie.description %></td>
      <td><%= serie.season %></td>
      <td><%= serie.duration %></td>
      <td><%= @tv_shows.find(serie.tv_show_id).name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/finish_signup.html.erb
<h1>Confirma tu Email y Contraseña</h1>

<%= form_for(current_user, url: finish_signup_path(current_user)) do |f| %>
  <% if @show_errors && current_user.errors.any? %>
    <h2>Errores encontrados:</h2>
    <ul>
      <% current_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= f.label :email %>
    <%= f.text_field :email, autofocus: true, value: '', placeholder: 'Example: email@me.com' %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.text_field :password, autofocus: false, value: '', placeholder: "123456" %>
  </div>

  <div class="actions">
    <%= f.submit 'Confirmar' %>
  </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="col-sm-3">
  <% if @user.avatar? %>
    <div class="circular--landscape">
      <%= image_tag @user.avatar(:medium) %>
    </div>
  <% else %>
    <div class="circular--landscape">
      <%= image_tag "http://file.vforum.vn/hinh/2014/5/anh-dai-dien-facebook-8.jpg" %>
    </div>
  <% end %>
</div>
<div class="col-sm-9 verticalLine">
  <%= link_to "", edit_user_registration_path(current_user), class: "btn btn-danger fa fa-pencil fa-lg" %>
  <span></span>
  <%if @user.role.to_s != 'child'%>
    <%= link_to "", register_path(:child => true), class: "btn btn-danger fa fa-user-plus fa-lg", style: "color:white" %>
  <%end%>
  <br></br>
  <p>
    <h4>Name</h4>
    <%= @user.first_name + ' ' + @user.last_name %>
  </p>
  <p>
    <h4>Mail</h4>
    <%= @user.email %>
  </p>
  <p>
    <h4>Permiso</h4>
    <%= @user.role.to_s %>
  </p>
</div>
<br>
<br>
<h4 style="color:rgb(38, 38, 38)">-</h4>
<h3>Añadidas Recientemente</h3>

<% @tv_shows.in_groups_of(4, false).each do |group| %>
  <div class='row'>
    <% group.each do |tv_show| %>
      <div class='col-md-3'>
        <%= image_tag(tv_show.cover(:medium), class: "img-responsive") %>
        <h3><%= tv_show.name %></h3>
        <%= link_to 'See more', tv_show_path(tv_show.id), class: 'btn btn-danger btn-sm' %>
        <% if user_signed_in? %>
          <%= link_to 'Recommend', new_mailingl_form_path(:subject => @user.first_name+' '+
          @user.last_name+' recommends you: '+tv_show.name,
          :body => "I think you'd love this tv serie.",
          :user_id => @user.id), class: 'btn btn-info btn-sm' %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<br>