config/routes.rb
Rails.application.routes.draw do

  resources :fav_episodes
  resources :notices
  get 'searcher/search'
  resources :fav_shows
  resources :episode_ratins
  resources :mailingl_forms
  devise_for :users,
    controllers: {:registrations => "registrations", omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :episode_comments
  resources :tv_show_comments
  resources :news
  resources :directors
  resources :actors
  resources :tv_shows do
    resources :episodes
  end
  resources :users
  get '/admin', to: 'users#admin'

  get '/fav', to: 'fav_shows#create'

  get '/fev', to: 'fav_episodes#create'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get '/user/favorite', to: 'users#favorite'

  root 'tv_shows#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
  has_many :episode_ratins, :dependent => :destroy
  has_many :episode_comments, :dependent => :destroy
  has_many :users, through: :episode_ratings
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :set_tv_show

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episode_comments = EpisodeComment.all
    @users = User.all
    @favs = FavEpisode.all
  end

  # GET /episodes/new
  def new
    @url = tv_show_episodes_path
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
    @url = tv_show_episode_path
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)
    respond_to do |format|
      if @tv_show.episodes << @episode
        format.html { redirect_to tv_show_path(@tv_show), notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    hash =  episode_params
    if hash["rating"].to_i > 5
      hash["rating"] = 5
    elsif hash["rating"].to_i < 0
      hash["rating"] = 0
    end
    respond_to do |format|
      if @episode.update(hash)
        format.html { redirect_to tv_show_path(@tv_show), notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to tv_show_path(@tv_show), notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    def set_tv_show
      @tv_show = TvShow.find(params[:tv_show_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :season, :description, :duration, :release_year, :tv_show_id, :seen, :favorite, :rating)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for([@tv_show, @episode], :url => @url) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, style: "color:rgb(38, 38, 38)" %>
  </div>

  <div class="field">
    <%= f.label :season %>
    <br>
    <%= f.number_field :season, style: "color:rgb(38, 38, 38)" %>
  </div>

  <%if @episode.seen%>
    <div class="field">
      <%= f.label :rating %>
      <br>
      <%= f.number_field :rating, style: "color:rgb(38, 38, 38)" %>
    </div>
  <%end%>


  <div class="field">
    <%= f.label :description %>
    <br>
    <%= f.text_area :description, cols: 40, rows: 8, style: "color:rgb(38, 38, 38)" %>
  </div>

  <div class="field">
    <%= f.label :favorite %>
    <br>
    <%= f.check_box :favorite %>
  </div>

  <div class="field">
    <%= f.label :seen %>
    <br>
    <%= f.check_box :seen %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <br>
    <%= f.number_field :duration, style: "color:rgb(38, 38, 38)" %>
  </div>

  <div class="field">
    <%= f.label :release_year %>
    <br>
    <%= f.number_field :release_year, style: "color:rgb(38, 38, 38)" %>
  </div>

  <div class="field">
    <%= f.hidden_field :tv_show_id, value: @tv_show.id %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :Save, class: "btn btn-danger", style: "color:white" %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editar capítulo a <%= @tv_show.name %></h1>

<%= render 'form' %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episodes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Season</th>
      <th>Description</th>
      <th>Duration</th>
      <th>Release year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.name %></td>
        <td><%= episode.season %></td>
        <td><%= episode.description %></td>
        <td><%= episode.duration %></td>
        <td><%= episode.release_year %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>Agregar Capítulo a <%= @tv_show.name %></h1>

<%= render 'form' %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="verticalLine" style="padding:15px">
  <p>
    <h3><%= @episode.name %></h3>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @episode.description %>
  </p>

  <p>
    <strong>Season:</strong>
    <%= @episode.season %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= @episode.duration %> minutes
  </p>

  <p>
    <strong>Release year:</strong>
    <%= @episode.release_year %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= @episode.rating %>
  </p>

  <p>
    <strong>Favorite</strong>
    <% if user_signed_in? %>
      <%if @favs != nil%>
        <%if @favs.find_by(user_id: current_user.id, episode_id: @episode.id) != nil%>
          <%= @favs.find_by(user_id: current_user.id, episode_id: @episode.id).favorite%>
        <%else%>
          <%= button_to 'Favorito', '/fev', method: :get, params: { user_id: current_user.id, episode_id: @episode.id }, class: "btn btn-danger" %>
        <%end%>
      <%else%>
        <%= "False"%>
        <%= button_to 'Favorito', '/fev', method: :get, params: { user_id: current_user.id, episode_id: @episode.id } %>
      <%end%>
    <% end %>
    <br>
  </p>
</div>


<h3>Comentarios</h3>
<br>
<% if user_signed_in? %>
  <% if current_user.role == 2 || current_user.id == @tv_show.user_id %>
    <%= link_to "", new_episode_comment_path(:episode_id=> @episode.id, :user_id => current_user.id), class: "btn btn-danger fa fa-plus fa-lg" %>
  <% end %>
<% end %>
<br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>User</th>
        <th>Comment</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <%@episode_comments.each do |t|%>
        <%if t.episode_id == @episode.id%>
        <%if user_signed_in? %>
            <tr>
              <td><%= @users.find(t.user_id).first_name%></td>
              <td><%= t.content %></td>
              <%if (t.user_id == current_user.id) or (current_user.role == 2)%>
                <td><%= link_to 'Delete', episode_comment_path(:id => t.id, :user_id => t.user_id,:episode_id => t.episode_id), method: :delete %></td
              <%end%>
            </tr>
          <%end%>
        <%end%>
      <%end%>
    </tbody>
  </table>