config/routes.rb
Rails.application.routes.draw do

  resources :fav_episodes
  resources :notices
  get 'searcher/search'
  resources :fav_shows
  resources :episode_ratins
  resources :mailingl_forms
  devise_for :users,
    controllers: {:registrations => "registrations", omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :episode_comments
  resources :tv_show_comments
  resources :news
  resources :directors
  resources :actors
  resources :tv_shows do
    resources :episodes
  end
  resources :users
  get '/admin', to: 'users#admin'

  get '/fav', to: 'fav_shows#create'

  get '/fev', to: 'fav_episodes#create'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  get '/user/favorite', to: 'users#favorite'

  root 'tv_shows#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/episode_ratin.rb
class EpisodeRatin < ApplicationRecord
  belongs_to :user
  belongs_to :episode
end

app/controllers/episode_ratins_controller.rb
class EpisodeRatinsController < ApplicationController
  before_action :set_episode_ratin, only: [:show, :edit, :update, :destroy]

  # GET /episode_ratins
  # GET /episode_ratins.json
  def index
    @episode_ratins = EpisodeRatin.all
  end

  # GET /episode_ratins/1
  # GET /episode_ratins/1.json
  def show
  end

  # GET /episode_ratins/new
  def new
    @episode_ratins = EpisodeRatin.all
    @episode_ratin = EpisodeRatin.new(:episode_id => params[:episode_id], :user_id => params[:user_id])

  end

  # GET /episode_ratins/1/edit
  def edit
  end

  # POST /episode_ratins
  # POST /episode_ratins.json
  def create
    @episode_ratin = EpisodeRatin.new(episode_ratin_params)
    if @episode_ratin.rating > 5
      @episode_ratin.rating = 5
    elsif @episode_ratin.rating < 0
      @episode_ratin.rating = 0
    end
    respond_to do |format|
      if @episode_ratin.save
        format.html { redirect_to @episode_ratin, notice: 'Episode ratin was successfully created.' }
        format.json { render :show, status: :created, location: @episode_ratin }
      else
        format.html { render :new }
        format.json { render json: @episode_ratin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episode_ratins/1
  # PATCH/PUT /episode_ratins/1.json
  def update
    hash =  episode_ratin_params
    if hash["rating"].to_i > 5
      hash["rating"] = 5
    elsif hash["rating"].to_i < 0
      hash["rating"] = 0
    end
    puts hash["rating"]
    respond_to do |format|
      if @episode_ratin.update(hash)
        format.html { redirect_to @episode_ratin, notice: 'Episode ratin was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode_ratin }
      else
        format.html { render :edit }
        format.json { render json: @episode_ratin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episode_ratins/1
  # DELETE /episode_ratins/1.json
  def destroy
    @episode_ratin.destroy
    respond_to do |format|
      format.html { redirect_to episode_ratins_url, notice: 'Episode ratin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode_ratin
      @episode_ratin = EpisodeRatin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_ratin_params
      params.require(:episode_ratin).permit(:rating, :favorite, :seen, :user_id, :episode_id)
    end
end

app/helpers/episode_ratins_helper.rb
module EpisodeRatinsHelper
end

app/views/episode_ratins/_form.html.erb
<%= form_for(episode_ratin) do |f| %>
  <% if episode_ratin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode_ratin.errors.count, "error") %> prohibited this episode_ratin from being saved:</h2>

      <ul>
      <% episode_ratin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :favorite %>
    <%= f.check_box :favorite %>
  </div>

  <div class="field">
    <%= f.label :seen %>
    <%= f.check_box :seen %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :episode_id %>
    <%= f.text_field :episode_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episode_ratins/_forma.html.erb
<%= form_for(episode_ratin) do |f| %>
  <% if episode_ratin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode_ratin.errors.count, "error") %> prohibited this episode_rating from being saved:</h2>

      <ul>
      <% episode_ratin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :favorite %>
    <%= f.check_box :favorite %>
  </div>

  <div class="field">
    <%= f.label :seen %>
    <%= f.check_box :seen %>
  </div>
  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, readonly: true%>
  </div>

  <div class="field">
    <%= f.label :episode_id %>
    <%= f.text_field :episode_id, readonly: true%>
  </div>

  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/episode_ratins/edit.html.erb
<h1>Editing Episode Ratin</h1>

<%= render 'forma', episode_ratin: @episode_ratin %>

<%= link_to 'Show', @episode_ratin %> |
<%= link_to 'Back', episode_ratins_path %>

app/views/episode_ratins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Episode Ratins</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Favorite</th>
      <th>Seen</th>
      <th>User</th>
      <th>Episode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episode_ratins.each do |episode_ratin| %>
      <tr>
        <td><%= episode_ratin.rating %></td>
        <td><%= episode_ratin.favorite %></td>
        <td><%= episode_ratin.seen %></td>
        <td><%= episode_ratin.user.id %></td>
        <td><%= episode_ratin.episode.id %></td>
        <td><%= link_to 'Show', episode_ratin %></td>
        <td><%= link_to 'Edit', edit_episode_ratin_path(episode_ratin) %></td>
        <td><%= link_to 'Destroy', episode_ratin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode Ratin', new_episode_ratin_path %>

app/views/episode_ratins/new.html.erb
<h1>New Episode Ratin</h1>
<%var = 0%>
<%if @episode_ratins == nil%>
  <%= render 'forma', episode_ratin: @episode_ratin %>
<%else%>
  <%@episode_ratins.each do |t|%>
    <%if (t.user_id.to_s == @episode_ratin.user_id.to_s) && (t.episode_id.to_s == @episode_ratin.episode_id.to_s)%>
      <% controller.redirect_to edit_episode_ratin_path(t.id) %>
      <%var = 1%>
      <%break%>
    <%end%>
  <%end%>
  <%if var == 0%>
    <%= render 'forma', episode_ratin: @episode_ratin %>
    <%= link_to 'Back', episode_ratins_path %>
  <%end%>
<%end%>

app/views/episode_ratins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @episode_ratin.rating %>
</p>

<p>
  <strong>Favorite:</strong>
  <%= @episode_ratin.favorite %>
</p>

<p>
  <strong>Seen:</strong>
  <%= @episode_ratin.seen %>
</p>

<p>
  <strong>User:</strong>
  <%= @episode_ratin.user %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @episode_ratin.episode %>
</p>

<%= link_to 'Edit', edit_episode_ratin_path(@episode_ratin) %> |
<%= link_to 'Back', episode_ratins_path %>